name: new_rezonate
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  shared_preferences: ^2.5.3
  firebase_messaging: ^16.0.0
  intl: ^0.18.1
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  image_picker: ^1.1.2
  sqflite: ^2.4.2
  path: ^1.9.1
  flutter_quill: ^8.0.0
  provider: ^6.1.1
  uuid: ^3.0.7
  table_calendar: ^3.0.9
  fl_chart: ^0.63.0
  firebase_storage: ^13.0.0
  permission_handler: ^12.0.1
  image_cropper: ^9.1.0
  url_launcher: ^6.3.0
  emoji_picker_flutter: ^4.3.0
  custom_refresh_indicator: ^3.0.0
  vibration: ^1.8.4
  showcaseview: ^4.0.1
  local_auth: ^2.1.6
  flutter_local_notifications: ^19.4.2
  timezone: ^0.10.1
  audioplayers: ^5.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  sqlite_viewer: ^1.0.5
  flutter_launcher_icons: ^0.14.3
  
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/appIcon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/Logo.png
    - assets/images/Full_logo.png
    - assets/images/appIcon.png
