name: new_rezonate
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  intl: ^0.18.1 
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  sqflite: ^2.3.0
  path: ^1.8.0
  flutter_quill: ^8.0.0
  provider: ^6.1.1
  uuid: ^3.0.7
  table_calendar: ^3.0.9 
  fl_chart: ^0.63.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6

flutter:
  assets:
    - assets/logo.png
  uses-material-design: true